import type { MagazineArticle, MagazineCategory, MagazineIssue } from "./magazine-types";

const image = (id: string) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=1400&q=82`;

export const magazineCategories: MagazineCategory[] = [
  { categoryId: "cat-runner", name: "Runner Spotlight", slug: "runner-spotlight", color: "#FF6B35" },
  { categoryId: "cat-club", name: "Club Feature", slug: "club-feature", color: "#00C9A7" },
  { categoryId: "cat-training", name: "Training", slug: "training", color: "#4A90E2" },
  { categoryId: "cat-fitness-coach", name: "Fitness Coach Column", slug: "fitness-coach", color: "#2563EB" },
  { categoryId: "cat-recovery", name: "Recovery", slug: "recovery", color: "#8B5CF6" },
  { categoryId: "cat-nutrition", name: "Nutrition", slug: "nutrition", color: "#F59E0B" },
  { categoryId: "cat-events", name: "Upcoming Event", slug: "event-preview", color: "#EF4444" },
  { categoryId: "cat-event-review", name: "Event Review", slug: "event-review", color: "#B91C1C" },
  { categoryId: "cat-community", name: "Community Story", slug: "community-story", color: "#10B981" },
  { categoryId: "cat-gear", name: "Gear Pick", slug: "gear-pick", color: "#111827" },
];

export const magazineIssues: MagazineIssue[] = [
  {
    issueId: "issue-003",
    slug: "volume-01-issue-03",
    title: "The Belonging Issue",
    subtitle: "Clubs, comeback miles, and the small rituals that keep runners connected.",
    description: "A global look at how ordinary runners build extraordinary consistency through community.",
    editorNote:
      "This volume is about the quiet power of showing up: the greeting before sunrise, the shared water stop, and the person who waits at the corner so nobody finishes alone.",
    coverImageUrl: image("photo-1500530855697-b586d89ba3ee"),
    volumeNumber: 1,
    issueNumber: 3,
    publicationDate: "2026-04-17",
    cadence: "biweekly",
    status: "published",
  },
  {
    issueId: "issue-002",
    slug: "volume-01-issue-02",
    title: "Stronger Together",
    subtitle: "Training plans, club culture, recovery wisdom, and gear that earns its place.",
    description: "Practical ideas for runners and walkers building momentum without burning out.",
    editorNote:
      "Progress is rarely loud. It usually looks like a better warm-up, a calmer pace, and friends who keep you honest when motivation dips.",
    coverImageUrl: image("photo-1486218119243-13883505764c"),
    volumeNumber: 1,
    issueNumber: 2,
    publicationDate: "2026-04-03",
    cadence: "biweekly",
    status: "published",
  },
  {
    issueId: "issue-001",
    slug: "volume-01-issue-01",
    title: "First Steps, Farther Places",
    subtitle: "Stories from walkers, new runners, and clubs making movement feel welcoming.",
    description: "The launch issue of RunNation Magazine, built around confidence, access, and joy.",
    editorNote:
      "Every running community begins with a first step. This opening volume celebrates the people who make that step feel possible.",
    coverImageUrl: image("photo-1464822759023-fed622ff2c3b"),
    volumeNumber: 1,
    issueNumber: 1,
    publicationDate: "2026-03-20",
    cadence: "biweekly",
    status: "published",
  },
];

export const magazineArticles: MagazineArticle[] = [
  {
    articleId: "art-001",
    issueId: "issue-003",
    issueSlug: "volume-01-issue-03",
    categorySlug: "runner-spotlight",
    slug: "the-runner-who-kept-the-corner",
    title: "The Runner Who Kept the Corner",
    subtitle: "How one Kampala runner turned a lonely bend into a weekly meeting point.",
    summary:
      "A short profile of patience, consistency, and the kind of leadership that does not need a microphone.",
    authorName: "Maya Okello",
    authorRole: "RunNation Editorial",
    heroImageUrl: image("photo-1476480862126-209bfaa8edc8"),
    readingTimeMinutes: 5,
    featuredQuote: "Community begins when someone decides the last runner matters as much as the first.",
    isFeatured: true,
    isEditorsPick: true,
    isPublished: true,
    publishDate: "2026-04-17",
    popularityScore: 98,
    body: [
      { type: "paragraph", text: "Before it became a club habit, it was just Joseph standing near the same corner every Saturday. He waited at the point where new runners usually slowed down, looked back, and wondered if they had taken on too much." },
      { type: "paragraph", text: "He did not shout instructions. He jogged beside people, asked how they were breathing, and reminded them that finishing slowly was still finishing. Within a few weeks, that corner had a name." },
      { type: "quote", text: "The corner became proof that nobody had to earn belonging by being fast.", attribution: "Joseph K." },
      { type: "heading", text: "A Small Ritual With Big Reach" },
      { type: "paragraph", text: "The club now uses the corner as a reset point. Faster runners loop back, walkers regroup, and first-timers learn the route without feeling abandoned. It is simple, but simple is often what survives." },
      { type: "bullets", items: ["Start with one visible meeting point.", "Give beginners a predictable place to reconnect.", "Make looping back a culture, not a punishment."] },
      { type: "paragraph", text: "Joseph says he is not building athletes first. He is building trust. The fitness follows." },
    ],
  },
  {
    articleId: "art-002",
    issueId: "issue-003",
    issueSlug: "volume-01-issue-03",
    categorySlug: "club-feature",
    slug: "nairobi-sunday-easy-crew",
    title: "Inside Nairobi’s Sunday Easy Crew",
    subtitle: "A club proving that easy days can be serious community work.",
    summary:
      "The weekly session has become part movement practice, part check-in, part neighborhood ritual.",
    authorName: "Daniel Reed",
    authorRole: "Club Correspondent",
    heroImageUrl: image("photo-1502224562085-639556652f33"),
    readingTimeMinutes: 6,
    featuredQuote: "Easy is not lazy. Easy is where people learn how to return.",
    isFeatured: false,
    isEditorsPick: false,
    isPublished: true,
    publishDate: "2026-04-17",
    popularityScore: 86,
    body: [
      { type: "paragraph", text: "The Sunday Easy Crew starts with a rule that sounds almost too gentle: nobody should finish more tired than they arrived. That rule has made the session one of the most consistent gatherings in the city." },
      { type: "heading", text: "Why It Works" },
      { type: "paragraph", text: "The route is short, the pace is conversational, and the finish always includes five minutes of stretching. Members say the predictability makes it easier to invite friends who are unsure whether they belong in a running space." },
      { type: "paragraph", text: "The club still has ambitious runners. But Sunday is protected. It is the day where performance takes a back seat to presence." },
    ],
  },
  {
    articleId: "art-003",
    issueId: "issue-003",
    issueSlug: "volume-01-issue-03",
    categorySlug: "fitness-coach",
    slug: "the-two-speed-week",
    title: "The Two-Speed Week",
    subtitle: "A practical rhythm for runners who want progress without complicated planning.",
    summary:
      "One easy session, one stronger session, and enough space between them to stay fresh.",
    authorName: "Aisha Morgan",
    authorRole: "Performance Coach",
    heroImageUrl: image("photo-1538805060514-97d9cc17730c"),
    readingTimeMinutes: 4,
    isFeatured: false,
    isPublished: true,
    publishDate: "2026-04-16",
    popularityScore: 91,
    body: [
      { type: "paragraph", text: "Many new runners do not need a complicated plan. They need a week that is easy to remember and forgiving enough to repeat. The two-speed week is built around that idea." },
      { type: "bullets", items: ["One session should feel comfortable enough to chat.", "One session can include short controlled efforts.", "Everything else can be walking, mobility, or rest."] },
      { type: "paragraph", text: "The secret is not the workout. It is the contrast. Easy days create room for stronger days, and stronger days give easy days a purpose." },
    ],
  },
  {
    articleId: "art-013",
    issueId: "issue-003",
    issueSlug: "volume-01-issue-03",
    categorySlug: "runner-spotlight",
    slug: "grace-who-found-her-evening-pace",
    title: "Grace Found Her Evening Pace",
    subtitle: "A runner spotlight on choosing consistency over comparison.",
    summary:
      "How a busy teacher rebuilt confidence with short evening runs and a club that celebrated showing up.",
    authorName: "RunNation Editorial",
    authorRole: "Runner Spotlight",
    heroImageUrl: image("photo-1483721310020-03333e577078"),
    readingTimeMinutes: 4,
    featuredQuote: "I stopped asking whether I was fast and started asking whether I was returning.",
    isFeatured: false,
    isEditorsPick: false,
    isPublished: true,
    publishDate: "2026-04-17",
    popularityScore: 84,
    body: [
      { type: "paragraph", text: "Grace used to believe running only counted when it looked impressive. Then she began taking twenty quiet minutes after work, looping the same neighborhood streets until the route felt like a promise." },
      { type: "paragraph", text: "The change was not dramatic at first. A little more calm. A little more sleep. A little more trust that the next run did not need to be perfect." },
      { type: "quote", text: "The club helped me stop apologizing for my pace.", attribution: "Grace N." },
    ],
  },
  {
    articleId: "art-014",
    issueId: "issue-003",
    issueSlug: "volume-01-issue-03",
    categorySlug: "club-feature",
    slug: "how-nairos-ugali-builds-belonging",
    title: "How Nairos Ugali Builds Belonging",
    subtitle: "A club feature on rituals, routes, and the food table after the finish.",
    summary:
      "The club keeps new members close with simple route briefings, flexible pace groups, and a finish that feels like family.",
    authorName: "Daniel Reed",
    authorRole: "Club Correspondent",
    heroImageUrl: image("photo-1517836357463-d25dfeac3438"),
    readingTimeMinutes: 5,
    isFeatured: false,
    isPublished: true,
    publishDate: "2026-04-17",
    popularityScore: 80,
    body: [
      { type: "paragraph", text: "Nairos Ugali has learned that a club is not built only on training. It is built on the small systems that help people feel expected before they feel experienced." },
      { type: "heading", text: "The Welcome Loop" },
      { type: "paragraph", text: "Every session starts with a route explanation, a pace check, and a reminder that nobody disappears from the group without someone noticing." },
    ],
  },
  {
    articleId: "art-015",
    issueId: "issue-003",
    issueSlug: "volume-01-issue-03",
    categorySlug: "community-story",
    slug: "submitted-story-the-first-friend-at-the-start-line",
    title: "Submitted Story: The First Friend at the Start Line",
    subtitle: "A community pick from a member who nearly turned around before her first event.",
    summary:
      "One greeting, one shared warm-up, and one finish-line photo changed how a new member saw the running community.",
    authorName: "Submitted by A. Namata",
    authorRole: "Community Submission",
    heroImageUrl: image("photo-1500534314209-a25ddb2bd429"),
    readingTimeMinutes: 4,
    featuredQuote: "Sometimes the whole event changes because one person says, stand with us.",
    isFeatured: false,
    isPublished: true,
    publishDate: "2026-04-16",
    popularityScore: 78,
    body: [
      { type: "paragraph", text: "I was already planning my excuse when someone asked if I wanted to warm up with their group. I did not know her name yet, but I knew I was no longer alone." },
      { type: "paragraph", text: "We started slowly. We laughed at the nerves. By the time the route opened, I had stopped thinking about leaving." },
      { type: "quote", text: "I finished because I had company before I had courage." },
    ],
  },
  {
    articleId: "art-016",
    issueId: "issue-003",
    issueSlug: "volume-01-issue-03",
    categorySlug: "community-story",
    slug: "submitted-story-why-we-walk-after-work",
    title: "Submitted Story: Why We Walk After Work",
    subtitle: "A user story about a small walking group that became the best hour of the week.",
    summary:
      "A simple routine grew into accountability, friendship, and a reason to leave the desk on time.",
    authorName: "Submitted by K. Wanjiru",
    authorRole: "Community Submission",
    heroImageUrl: image("photo-1500530855697-b586d89ba3ee"),
    readingTimeMinutes: 4,
    isFeatured: false,
    isPublished: true,
    publishDate: "2026-04-16",
    popularityScore: 76,
    body: [
      { type: "paragraph", text: "Our walking group started because three of us were tired of saying we would exercise tomorrow. We chose a short route and a time that made no one feel brave." },
      { type: "paragraph", text: "Now the walk is less about steps and more about returning to ourselves after the day has taken what it takes." },
    ],
  },
  {
    articleId: "art-004",
    issueId: "issue-003",
    issueSlug: "volume-01-issue-03",
    categorySlug: "nutrition",
    slug: "breakfast-before-a-long-walk",
    title: "Breakfast Before a Long Walk",
    subtitle: "Simple fuel ideas for walkers and runners starting early.",
    summary:
      "A gentle guide to pre-session meals that are affordable, familiar, and stomach-friendly.",
    authorName: "Nia Patel",
    authorRole: "Nutrition Writer",
    heroImageUrl: image("photo-1498837167922-ddd27525d352"),
    readingTimeMinutes: 4,
    isFeatured: false,
    isPublished: true,
    publishDate: "2026-04-15",
    popularityScore: 73,
    body: [
      { type: "paragraph", text: "A good pre-walk breakfast does not have to be special. It should be familiar, light enough to move with, and steady enough to keep your energy from disappearing halfway through the route." },
      { type: "heading", text: "Keep It Familiar" },
      { type: "paragraph", text: "Banana with peanut butter, toast with eggs, porridge, fruit and yogurt, or tea with a small sandwich can all work. The best choice is the one your body already understands." },
      { type: "quote", text: "Fuel is not a performance luxury. It is care for the body doing the work." },
    ],
  },
  {
    articleId: "art-005",
    issueId: "issue-003",
    issueSlug: "volume-01-issue-03",
    categorySlug: "event-preview",
    slug: "the-city-loop-preview",
    title: "Event Preview: The City Loop",
    subtitle: "What to expect from a route built for first-timers and club energy.",
    summary:
      "A route preview with pacing notes, crowd tips, and why the finish zone matters.",
    authorName: "RunNation Desk",
    authorRole: "Events Team",
    heroImageUrl: image("photo-1517649763962-0c623066013b"),
    readingTimeMinutes: 5,
    isFeatured: false,
    isPublished: true,
    publishDate: "2026-04-14",
    popularityScore: 82,
    body: [
      { type: "paragraph", text: "The City Loop is designed to feel welcoming before it feels competitive. The opening kilometer is wide, the middle section has the most shade, and the final turn brings runners back toward the loudest part of the crowd." },
      { type: "bullets", items: ["Start easier than the crowd pulls you.", "Use the shaded middle section to settle.", "Look for club flags near the finish to reconnect quickly."] },
      { type: "paragraph", text: "If this is your first event, make the goal simple: start calm, finish proud, and let the community carry the nervous parts." },
    ],
  },
  {
    articleId: "art-018",
    issueId: "issue-003",
    issueSlug: "volume-01-issue-03",
    categorySlug: "event-review",
    slug: "event-review-lakeside-10k",
    title: "Event Review: Lakeside 10K",
    subtitle: "What worked, what runners loved, and what the next event can improve.",
    summary:
      "A concise review of a concluded event, from route energy to hydration points and finish-zone flow.",
    authorName: "RunNation Events",
    authorRole: "Events Team",
    heroImageUrl: image("photo-1461896836934-ffe607ba8211"),
    readingTimeMinutes: 5,
    isFeatured: false,
    isPublished: true,
    publishDate: "2026-04-13",
    popularityScore: 83,
    body: [
      { type: "paragraph", text: "The Lakeside 10K delivered what runners remember most: a calm start, a scenic middle section, and a finish zone where clubs could find each other quickly." },
      { type: "heading", text: "Highlights" },
      { type: "bullets", items: ["Clear route markers in the first half.", "Strong club support near the final kilometer.", "A finish area that encouraged photos and regrouping."] },
      { type: "paragraph", text: "The next edition can improve by adding one more water point before the longest exposed stretch." },
    ],
  },
  {
    articleId: "art-019",
    issueId: "issue-003",
    issueSlug: "volume-01-issue-03",
    categorySlug: "gear-pick",
    slug: "gear-pick-the-everyday-cap",
    title: "Gear Pick: The Everyday Cap",
    subtitle: "A small item that earns its place in sunny walks, rainy starts, and travel runs.",
    summary:
      "Why a light, washable cap can be one of the most useful pieces in a beginner-friendly kit.",
    authorName: "RunNation Gear Desk",
    authorRole: "Gear Pick",
    heroImageUrl: image("photo-1500534314209-a25ddb2bd429"),
    readingTimeMinutes: 3,
    isFeatured: false,
    isPublished: true,
    publishDate: "2026-04-12",
    popularityScore: 68,
    body: [
      { type: "paragraph", text: "The best gear is often the thing you stop thinking about. A light cap keeps sun out of your eyes, handles a little rain, and makes early starts feel more prepared." },
      { type: "bullets", items: ["Choose breathable fabric.", "Check that the brim does not bounce.", "Pick a color you will actually wear."] },
    ],
  },
  {
    articleId: "art-006",
    issueId: "issue-002",
    issueSlug: "volume-01-issue-02",
    categorySlug: "recovery",
    slug: "the-rest-day-that-still-counts",
    title: "The Rest Day That Still Counts",
    subtitle: "Why recovery is not a break from progress but part of the plan.",
    summary: "A calm reminder that adaptation happens when the body gets time to absorb the work.",
    authorName: "Leah Mensah",
    authorRole: "Wellness Editor",
    heroImageUrl: image("photo-1506126613408-eca07ce68773"),
    readingTimeMinutes: 4,
    featuredQuote: "Rest is not falling behind. Rest is where the training becomes yours.",
    isFeatured: true,
    isPublished: true,
    publishDate: "2026-04-03",
    popularityScore: 89,
    body: [
      { type: "paragraph", text: "A rest day can feel strange when you are excited about progress. But the body does not become stronger during the hardest minutes of training. It becomes stronger when it repairs." },
      { type: "paragraph", text: "For most runners and walkers, a useful rest day is not dramatic. It is sleep, water, a short walk if desired, and the confidence to leave tomorrow’s energy untouched." },
      { type: "separator" },
      { type: "paragraph", text: "The goal is not to do nothing forever. The goal is to return with enough freshness to enjoy the next session." },
    ],
  },
  {
    articleId: "art-007",
    issueId: "issue-002",
    issueSlug: "volume-01-issue-02",
    categorySlug: "gear-pick",
    slug: "the-light-jacket-test",
    title: "The Light Jacket Test",
    subtitle: "How to choose a layer that helps more than it annoys.",
    summary: "A practical gear note for changing weather, morning starts, and travel runs.",
    authorName: "Owen Hart",
    authorRole: "Gear Notes",
    heroImageUrl: image("photo-1500534314209-a25ddb2bd429"),
    readingTimeMinutes: 3,
    isFeatured: false,
    isPublished: true,
    publishDate: "2026-04-02",
    popularityScore: 62,
    body: [
      { type: "paragraph", text: "A good light jacket should disappear once you start moving. If it traps too much heat, swings heavily when tied around your waist, or feels noisy with every arm swing, it may not earn its space." },
      { type: "bullets", items: ["Look for breathable fabric.", "Check pocket security before carrying keys.", "Choose visibility if you run before sunrise."] },
    ],
  },
  {
    articleId: "art-008",
    issueId: "issue-002",
    issueSlug: "volume-01-issue-02",
    categorySlug: "community-story",
    slug: "walking-group-that-became-a-club",
    title: "The Walking Group That Became a Club",
    subtitle: "A community story about starting with conversation and growing into structure.",
    summary: "How a small group used consistency, not speed, to create a durable local club.",
    authorName: "Fatima Noor",
    authorRole: "Community Writer",
    heroImageUrl: image("photo-1501555088652-021faa106b9b"),
    readingTimeMinutes: 5,
    isFeatured: false,
    isPublished: true,
    publishDate: "2026-04-01",
    popularityScore: 79,
    body: [
      { type: "paragraph", text: "The group did not call itself a club at first. It was three neighbors meeting after work because walking alone felt easy to cancel. The route was twenty minutes and ended near a fruit stand." },
      { type: "paragraph", text: "By month two, they had a route name. By month four, they had a WhatsApp group. By month six, new people were asking where to register." },
      { type: "quote", text: "Structure arrived after belonging, not before it." },
    ],
  },
  {
    articleId: "art-009",
    issueId: "issue-002",
    issueSlug: "volume-01-issue-02",
    categorySlug: "training",
    slug: "hills-without-fear",
    title: "Hills Without Fear",
    subtitle: "A beginner-friendly way to make climbing part of your week.",
    summary: "Short hills can improve strength and confidence when approached patiently.",
    authorName: "Sam Rivera",
    authorRole: "Coach",
    heroImageUrl: image("photo-1500534314209-a25ddb2bd429"),
    readingTimeMinutes: 4,
    isFeatured: false,
    isPublished: true,
    publishDate: "2026-03-31",
    popularityScore: 75,
    body: [
      { type: "paragraph", text: "Hills become less intimidating when you stop treating them like tests. Think of them as strength practice. Short, controlled climbs teach posture, rhythm, and patience." },
      { type: "bullets", items: ["Keep your steps short.", "Look slightly ahead, not at the top.", "Walk early if your breathing spikes."] },
      { type: "paragraph", text: "A hill session should end with confidence, not punishment." },
    ],
  },
  {
    articleId: "art-010",
    issueId: "issue-001",
    issueSlug: "volume-01-issue-01",
    categorySlug: "runner-spotlight",
    slug: "first-5k-first-finish-line",
    title: "First 5K, First Finish Line",
    subtitle: "A new runner’s account of turning nerves into a finish-line smile.",
    summary: "An honest, encouraging story for anyone preparing for a first event.",
    authorName: "RunNation Editorial",
    authorRole: "Spotlight Desk",
    heroImageUrl: image("photo-1518611012118-696072aa579a"),
    readingTimeMinutes: 5,
    isFeatured: true,
    isPublished: true,
    publishDate: "2026-03-20",
    popularityScore: 94,
    body: [
      { type: "paragraph", text: "The night before her first 5K, Amara laid out her shoes, pinned her bib twice, and still wondered if everyone else would look like they knew what they were doing." },
      { type: "paragraph", text: "By the second kilometer, the fear had become focus. By the fourth, focus had become stubborn joy. At the finish, she did not check her time first. She looked back for the friend who started beside her." },
      { type: "quote", text: "The medal mattered. The memory mattered more." },
    ],
  },
  {
    articleId: "art-011",
    issueId: "issue-001",
    issueSlug: "volume-01-issue-01",
    categorySlug: "club-feature",
    slug: "how-to-welcome-new-members",
    title: "How Clubs Can Welcome New Members",
    subtitle: "Five small gestures that make a first session less intimidating.",
    summary: "A practical club culture guide for coordinators and friendly regulars.",
    authorName: "Clara James",
    authorRole: "Club Culture",
    heroImageUrl: image("photo-1520975682031-a2cfe6aeba80"),
    readingTimeMinutes: 4,
    isFeatured: false,
    isPublished: true,
    publishDate: "2026-03-19",
    popularityScore: 81,
    body: [
      { type: "paragraph", text: "A new member decides quickly whether a club feels safe. The route matters, but the welcome matters more." },
      { type: "bullets", items: ["Say names slowly and repeat them.", "Explain the route before moving.", "Assign a friendly regular to check in.", "Make the slowest option visible.", "Celebrate attendance, not only pace."] },
    ],
  },
  {
    articleId: "art-012",
    issueId: "issue-001",
    issueSlug: "volume-01-issue-01",
    categorySlug: "community-story",
    slug: "from-solo-miles-to-shared-routes",
    title: "From Solo Miles to Shared Routes",
    subtitle: "Why many runners stay consistent once they stop doing everything alone.",
    summary: "A community-centered reflection on accountability, friendship, and showing up.",
    authorName: "Mika Tan",
    authorRole: "Community Desk",
    heroImageUrl: image("photo-1469474968028-56623f02e42e"),
    readingTimeMinutes: 5,
    isFeatured: false,
    isPublished: true,
    publishDate: "2026-03-18",
    popularityScore: 77,
    body: [
      { type: "paragraph", text: "Solo miles can be peaceful. Shared routes can be sustaining. The difference is not that one is better. It is that community gives your intention somewhere to land." },
      { type: "paragraph", text: "When someone expects you at the start, the decision to move becomes easier. When someone asks how your knee feels, the app becomes more than data. It becomes care." },
    ],
  },
];

export function getCategory(slug: string) {
  return magazineCategories.find((category) => category.slug === slug) ?? magazineCategories[0];
}

export function getLatestIssue() {
  return [...magazineIssues].sort((a, b) => b.publicationDate.localeCompare(a.publicationDate))[0];
}

export function getArticlesForIssue(issueSlug: string) {
  return magazineArticles.filter((article) => article.issueSlug === issueSlug && article.isPublished);
}

export function getArticleBySlug(articleSlug: string) {
  return magazineArticles.find((article) => article.slug === articleSlug && article.isPublished) ?? null;
}

export function getIssueBySlug(issueSlug: string) {
  return magazineIssues.find((issue) => issue.slug === issueSlug && issue.status === "published") ?? null;
}

export function getRelatedArticles(article: MagazineArticle, limit = 3) {
  return magazineArticles
    .filter((candidate) => candidate.articleId !== article.articleId && candidate.isPublished)
    .sort((a, b) => {
      if (a.categorySlug === article.categorySlug && b.categorySlug !== article.categorySlug) return -1;
      if (a.categorySlug !== article.categorySlug && b.categorySlug === article.categorySlug) return 1;
      return b.popularityScore - a.popularityScore;
    })
    .slice(0, limit);
}
