export type CountryOption = {
  name: string;
  iso_alpha2: string;
};

export const WORLD_COUNTRIES: CountryOption[] = [
  { name: "Afghanistan", iso_alpha2: "AF" },
  { name: "Albania", iso_alpha2: "AL" },
  { name: "Algeria", iso_alpha2: "DZ" },
  { name: "Andorra", iso_alpha2: "AD" },
  { name: "Angola", iso_alpha2: "AO" },
  { name: "Antigua and Barbuda", iso_alpha2: "AG" },
  { name: "Argentina", iso_alpha2: "AR" },
  { name: "Armenia", iso_alpha2: "AM" },
  { name: "Australia", iso_alpha2: "AU" },
  { name: "Austria", iso_alpha2: "AT" },
  { name: "Azerbaijan", iso_alpha2: "AZ" },
  { name: "Bahamas", iso_alpha2: "BS" },
  { name: "Bahrain", iso_alpha2: "BH" },
  { name: "Bangladesh", iso_alpha2: "BD" },
  { name: "Barbados", iso_alpha2: "BB" },
  { name: "Belarus", iso_alpha2: "BY" },
  { name: "Belgium", iso_alpha2: "BE" },
  { name: "Belize", iso_alpha2: "BZ" },
  { name: "Benin", iso_alpha2: "BJ" },
  { name: "Bhutan", iso_alpha2: "BT" },
  { name: "Bolivia", iso_alpha2: "BO" },
  { name: "Bosnia and Herzegovina", iso_alpha2: "BA" },
  { name: "Botswana", iso_alpha2: "BW" },
  { name: "Brazil", iso_alpha2: "BR" },
  { name: "Brunei", iso_alpha2: "BN" },
  { name: "Bulgaria", iso_alpha2: "BG" },
  { name: "Burkina Faso", iso_alpha2: "BF" },
  { name: "Burundi", iso_alpha2: "BI" },
  { name: "Cabo Verde", iso_alpha2: "CV" },
  { name: "Cambodia", iso_alpha2: "KH" },
  { name: "Cameroon", iso_alpha2: "CM" },
  { name: "Canada", iso_alpha2: "CA" },
  { name: "Central African Republic", iso_alpha2: "CF" },
  { name: "Chad", iso_alpha2: "TD" },
  { name: "Chile", iso_alpha2: "CL" },
  { name: "China", iso_alpha2: "CN" },
  { name: "Colombia", iso_alpha2: "CO" },
  { name: "Comoros", iso_alpha2: "KM" },
  { name: "Congo (Congo-Brazzaville)", iso_alpha2: "CG" },
  { name: "Costa Rica", iso_alpha2: "CR" },
  { name: "Croatia", iso_alpha2: "HR" },
  { name: "Cuba", iso_alpha2: "CU" },
  { name: "Cyprus", iso_alpha2: "CY" },
  { name: "Czechia", iso_alpha2: "CZ" },
  { name: "Democratic Republic of the Congo", iso_alpha2: "CD" },
  { name: "Denmark", iso_alpha2: "DK" },
  { name: "Djibouti", iso_alpha2: "DJ" },
  { name: "Dominica", iso_alpha2: "DM" },
  { name: "Dominican Republic", iso_alpha2: "DO" },
  { name: "Ecuador", iso_alpha2: "EC" },
  { name: "Egypt", iso_alpha2: "EG" },
  { name: "El Salvador", iso_alpha2: "SV" },
  { name: "Equatorial Guinea", iso_alpha2: "GQ" },
  { name: "Eritrea", iso_alpha2: "ER" },
  { name: "Estonia", iso_alpha2: "EE" },
  { name: "Eswatini", iso_alpha2: "SZ" },
  { name: "Ethiopia", iso_alpha2: "ET" },
  { name: "Fiji", iso_alpha2: "FJ" },
  { name: "Finland", iso_alpha2: "FI" },
  { name: "France", iso_alpha2: "FR" },
  { name: "Gabon", iso_alpha2: "GA" },
  { name: "Gambia", iso_alpha2: "GM" },
  { name: "Georgia", iso_alpha2: "GE" },
  { name: "Germany", iso_alpha2: "DE" },
  { name: "Ghana", iso_alpha2: "GH" },
  { name: "Greece", iso_alpha2: "GR" },
  { name: "Grenada", iso_alpha2: "GD" },
  { name: "Guatemala", iso_alpha2: "GT" },
  { name: "Guinea", iso_alpha2: "GN" },
  { name: "Guinea-Bissau", iso_alpha2: "GW" },
  { name: "Guyana", iso_alpha2: "GY" },
  { name: "Haiti", iso_alpha2: "HT" },
  { name: "Honduras", iso_alpha2: "HN" },
  { name: "Hungary", iso_alpha2: "HU" },
  { name: "Iceland", iso_alpha2: "IS" },
  { name: "India", iso_alpha2: "IN" },
  { name: "Indonesia", iso_alpha2: "ID" },
  { name: "Iran", iso_alpha2: "IR" },
  { name: "Iraq", iso_alpha2: "IQ" },
  { name: "Ireland", iso_alpha2: "IE" },
  { name: "Israel", iso_alpha2: "IL" },
  { name: "Italy", iso_alpha2: "IT" },
  { name: "Jamaica", iso_alpha2: "JM" },
  { name: "Japan", iso_alpha2: "JP" },
  { name: "Jordan", iso_alpha2: "JO" },
  { name: "Kazakhstan", iso_alpha2: "KZ" },
  { name: "Kenya", iso_alpha2: "KE" },
  { name: "Kiribati", iso_alpha2: "KI" },
  { name: "Kuwait", iso_alpha2: "KW" },
  { name: "Kyrgyzstan", iso_alpha2: "KG" },
  { name: "Laos", iso_alpha2: "LA" },
  { name: "Latvia", iso_alpha2: "LV" },
  { name: "Lebanon", iso_alpha2: "LB" },
  { name: "Lesotho", iso_alpha2: "LS" },
  { name: "Liberia", iso_alpha2: "LR" },
  { name: "Libya", iso_alpha2: "LY" },
  { name: "Liechtenstein", iso_alpha2: "LI" },
  { name: "Lithuania", iso_alpha2: "LT" },
  { name: "Luxembourg", iso_alpha2: "LU" },
  { name: "Madagascar", iso_alpha2: "MG" },
  { name: "Malawi", iso_alpha2: "MW" },
  { name: "Malaysia", iso_alpha2: "MY" },
  { name: "Maldives", iso_alpha2: "MV" },
  { name: "Mali", iso_alpha2: "ML" },
  { name: "Malta", iso_alpha2: "MT" },
  { name: "Marshall Islands", iso_alpha2: "MH" },
  { name: "Mauritania", iso_alpha2: "MR" },
  { name: "Mauritius", iso_alpha2: "MU" },
  { name: "Mexico", iso_alpha2: "MX" },
  { name: "Micronesia", iso_alpha2: "FM" },
  { name: "Moldova", iso_alpha2: "MD" },
  { name: "Monaco", iso_alpha2: "MC" },
  { name: "Mongolia", iso_alpha2: "MN" },
  { name: "Montenegro", iso_alpha2: "ME" },
  { name: "Morocco", iso_alpha2: "MA" },
  { name: "Mozambique", iso_alpha2: "MZ" },
  { name: "Myanmar", iso_alpha2: "MM" },
  { name: "Namibia", iso_alpha2: "NA" },
  { name: "Nauru", iso_alpha2: "NR" },
  { name: "Nepal", iso_alpha2: "NP" },
  { name: "Netherlands", iso_alpha2: "NL" },
  { name: "New Zealand", iso_alpha2: "NZ" },
  { name: "Nicaragua", iso_alpha2: "NI" },
  { name: "Niger", iso_alpha2: "NE" },
  { name: "Nigeria", iso_alpha2: "NG" },
  { name: "North Korea", iso_alpha2: "KP" },
  { name: "North Macedonia", iso_alpha2: "MK" },
  { name: "Norway", iso_alpha2: "NO" },
  { name: "Oman", iso_alpha2: "OM" },
  { name: "Pakistan", iso_alpha2: "PK" },
  { name: "Palau", iso_alpha2: "PW" },
  { name: "Panama", iso_alpha2: "PA" },
  { name: "Papua New Guinea", iso_alpha2: "PG" },
  { name: "Paraguay", iso_alpha2: "PY" },
  { name: "Peru", iso_alpha2: "PE" },
  { name: "Philippines", iso_alpha2: "PH" },
  { name: "Poland", iso_alpha2: "PL" },
  { name: "Portugal", iso_alpha2: "PT" },
  { name: "Qatar", iso_alpha2: "QA" },
  { name: "Romania", iso_alpha2: "RO" },
  { name: "Russia", iso_alpha2: "RU" },
  { name: "Rwanda", iso_alpha2: "RW" },
  { name: "Saint Kitts and Nevis", iso_alpha2: "KN" },
  { name: "Saint Lucia", iso_alpha2: "LC" },
  { name: "Saint Vincent and the Grenadines", iso_alpha2: "VC" },
  { name: "Samoa", iso_alpha2: "WS" },
  { name: "San Marino", iso_alpha2: "SM" },
  { name: "Sao Tome and Principe", iso_alpha2: "ST" },
  { name: "Saudi Arabia", iso_alpha2: "SA" },
  { name: "Senegal", iso_alpha2: "SN" },
  { name: "Serbia", iso_alpha2: "RS" },
  { name: "Seychelles", iso_alpha2: "SC" },
  { name: "Sierra Leone", iso_alpha2: "SL" },
  { name: "Singapore", iso_alpha2: "SG" },
  { name: "Slovakia", iso_alpha2: "SK" },
  { name: "Slovenia", iso_alpha2: "SI" },
  { name: "Solomon Islands", iso_alpha2: "SB" },
  { name: "Somalia", iso_alpha2: "SO" },
  { name: "South Africa", iso_alpha2: "ZA" },
  { name: "South Korea", iso_alpha2: "KR" },
  { name: "South Sudan", iso_alpha2: "SS" },
  { name: "Spain", iso_alpha2: "ES" },
  { name: "Sri Lanka", iso_alpha2: "LK" },
  { name: "Sudan", iso_alpha2: "SD" },
  { name: "Suriname", iso_alpha2: "SR" },
  { name: "Sweden", iso_alpha2: "SE" },
  { name: "Switzerland", iso_alpha2: "CH" },
  { name: "Syria", iso_alpha2: "SY" },
  { name: "Taiwan", iso_alpha2: "TW" },
  { name: "Tajikistan", iso_alpha2: "TJ" },
  { name: "Tanzania", iso_alpha2: "TZ" },
  { name: "Thailand", iso_alpha2: "TH" },
  { name: "Timor-Leste", iso_alpha2: "TL" },
  { name: "Togo", iso_alpha2: "TG" },
  { name: "Tonga", iso_alpha2: "TO" },
  { name: "Trinidad and Tobago", iso_alpha2: "TT" },
  { name: "Tunisia", iso_alpha2: "TN" },
  { name: "Turkey", iso_alpha2: "TR" },
  { name: "Turkmenistan", iso_alpha2: "TM" },
  { name: "Tuvalu", iso_alpha2: "TV" },
  { name: "Uganda", iso_alpha2: "UG" },
  { name: "Ukraine", iso_alpha2: "UA" },
  { name: "United Arab Emirates", iso_alpha2: "AE" },
  { name: "United Kingdom", iso_alpha2: "GB" },
  { name: "United States", iso_alpha2: "US" },
  { name: "Uruguay", iso_alpha2: "UY" },
  { name: "Uzbekistan", iso_alpha2: "UZ" },
  { name: "Vanuatu", iso_alpha2: "VU" },
  { name: "Vatican City", iso_alpha2: "VA" },
  { name: "Venezuela", iso_alpha2: "VE" },
  { name: "Vietnam", iso_alpha2: "VN" },
  { name: "Yemen", iso_alpha2: "YE" },
  { name: "Zambia", iso_alpha2: "ZM" },
  { name: "Zimbabwe", iso_alpha2: "ZW" },
];
