begin;

create table if not exists public.faq_entries (
  faq_id bigint generated by default as identity primary key,
  question text not null,
  answer text not null,
  display_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

create index if not exists idx_faq_entries_display_order
  on public.faq_entries (display_order, faq_id);

insert into public.faq_entries (question, answer, display_order, is_active)
values
  (
    'How do I join an event?',
    'Open Events, choose an event that matches your country or is marked virtual, then tap Participate. Free events add you straight to participants, club-approved events go to review, and paid events wait for payment confirmation.',
    10,
    true
  ),
  (
    'Why can''t I join some events?',
    'Some non-virtual events are limited to your registered country. You may also need club approval or payment before your slot is confirmed.',
    20,
    true
  ),
  (
    'What does Private Mode do?',
    'Private Mode hides your data from public leaderboards and community-style views where the app supports that setting. You can still use your core account features normally.',
    30,
    true
  ),
  (
    'How are treadmill activities approved?',
    'Treadmill sessions go to the admin review queue with the proof photo you submit. An admin checks the evidence before the activity is accepted into your records.',
    40,
    true
  ),
  (
    'Why does my profile completion matter?',
    'Profile completion helps unlock a cleaner app experience by making sure your core details, goals, verification state, and admin requirements are properly set up.',
    50,
    true
  ),
  (
    'How do payments work in RunNation?',
    'Subscriptions, paid events, and any approved payment-based workflows may require confirmation before access is granted. Where a fee applies, the app or the responsible admin should communicate the payment instructions clearly.',
    60,
    true
  ),
  (
    'How do I contact an admin quickly?',
    'Go to Settings > Help. You will find admin contacts there with quick WhatsApp and email actions where contact details are available.',
    70,
    true
  ),
  (
    'Can I submit suggestions or report a problem?',
    'Yes. Use Settings > Suggestions to send feedback. Choose the category that best matches your issue so the team can route it faster.',
    80,
    true
  )
on conflict do nothing;

commit;
