create table if not exists public.daily_run_goal (
  daily_run_goal_id bigint generated by default as identity primary key,
  registration_id uuid not null references public.registrations(registration_id) on delete cascade,
  start_date date not null,
  end_date date not null,
  target_percent numeric not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint daily_run_goal_date_check check (end_date >= start_date),
  constraint daily_run_goal_target_check check (target_percent >= 1 and target_percent <= 100)
);

create index if not exists idx_daily_run_goal_registration_id
  on public.daily_run_goal using btree (registration_id);

alter table public.daily_run_goal enable row level security;

drop policy if exists "Users can read their daily run goals" on public.daily_run_goal;
create policy "Users can read their daily run goals"
  on public.daily_run_goal
  for select
  using (auth.uid() = registration_id);

drop policy if exists "Users can insert their daily run goals" on public.daily_run_goal;
create policy "Users can insert their daily run goals"
  on public.daily_run_goal
  for insert
  with check (auth.uid() = registration_id);

drop policy if exists "Users can update their daily run goals" on public.daily_run_goal;
create policy "Users can update their daily run goals"
  on public.daily_run_goal
  for update
  using (auth.uid() = registration_id)
  with check (auth.uid() = registration_id);
