with sample_articles(
  article_id,
  registration_id,
  page,
  author,
  article_date,
  title,
  body,
  picture_link,
  external_link,
  source_table,
  source_id
) as (
  values
    (
      '1b9b9d11-34d6-4f5f-9a46-7341b4f70001'::uuid,
      null::text,
      'News',
      'RunNation News Desk',
      current_date,
      'Neighborhood Running Crews Turn Streets Into Meeting Places',
      $$Across several towns, small running crews are changing how people use familiar streets. What begins as a few friends meeting before work often grows into a dependable community routine. Runners say the best groups are not built around speed, but around a clear route, a visible meeting point, and a culture where new members are noticed quickly.$$,
      'https://images.unsplash.com/photo-1552674605-db6ffd4facb5?auto=format&fit=crop&w=1400&q=82',
      null::text,
      'sample_seed',
      '1b9b9d11-34d6-4f5f-9a46-7341b4f70001'::uuid
    ),
    (
      '1b9b9d11-34d6-4f5f-9a46-7341b4f70002'::uuid,
      null::text,
      'News',
      'RunNation News Desk',
      current_date - 1,
      'Morning Runs Become A Practical Habit For Busy Workers',
      $$More workers are choosing early morning runs because the time feels protected before messages, traffic, school runs, and meetings begin. Coaches say the trend is strongest among beginners who want a simple routine rather than a complicated training plan. The advice remains gentle: start with short routes, repeat them often, and avoid turning every run into a race.$$,
      'https://images.unsplash.com/photo-1486218119243-13883505764c?auto=format&fit=crop&w=1400&q=82',
      null::text,
      'sample_seed',
      '1b9b9d11-34d6-4f5f-9a46-7341b4f70002'::uuid
    ),
    (
      '1b9b9d11-34d6-4f5f-9a46-7341b4f70003'::uuid,
      null::text,
      'News',
      'RunNation News Desk',
      current_date - 2,
      'Schools Use Short Runs To Build Confidence And Teamwork',
      $$Schools are using short runs, relay days, and walk-run challenges to make movement feel positive for learners. Teachers say inclusive events work best when the route is clear, the distance is realistic, and every child has a role. The aim is not only fitness. It is confidence, cooperation, and a shared reason to celebrate effort.$$,
      'https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=1400&q=82',
      null::text,
      'sample_seed',
      '1b9b9d11-34d6-4f5f-9a46-7341b4f70003'::uuid
    ),
    (
      '2b9b9d11-34d6-4f5f-9a46-7341b4f70001'::uuid,
      null::text,
      'Events',
      'RunNation Events Team',
      current_date + 5,
      'Kasangati Community 5K Opens With A Beginner Friendly Route',
      $$The Kasangati Community 5K is inviting runners, walkers, clubs, families, and first-time participants to join a friendly local event. Organizers describe the course as steady and welcoming, with support points planned along the route. The event story focuses on participation first, giving new runners a realistic goal and experienced runners a reason to support others.$$,
      'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1400&q=82',
      null::text,
      'sample_seed',
      '2b9b9d11-34d6-4f5f-9a46-7341b4f70001'::uuid
    ),
    (
      '2b9b9d11-34d6-4f5f-9a46-7341b4f70002'::uuid,
      null::text,
      'Events',
      'RunNation Events Team',
      current_date + 12,
      'Charity Run Will Support Youth Sports Programs',
      $$A new charity run will raise support for youth sports programs and community play spaces. Organizers want the event to feel open to schools, institutions, companies, clubs, and families, so the program includes shorter participation options. The magazine preview helps readers understand the cause, not just the distance, and invites runners to bring friends.$$,
      'https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=1400&q=82',
      null::text,
      'sample_seed',
      '2b9b9d11-34d6-4f5f-9a46-7341b4f70002'::uuid
    ),
    (
      '2b9b9d11-34d6-4f5f-9a46-7341b4f70003'::uuid,
      null::text,
      'Events',
      'RunNation Events Team',
      current_date + 20,
      'Club Relay Weekend Puts Teamwork At The Centre',
      $$The upcoming club relay weekend gives running groups a different kind of challenge. Instead of focusing only on individual pace, teams will plan handovers, cheer one another, and celebrate consistency across mixed ability groups. Organizers expect club members, institutions, and corporate teams to join, with the finish area designed as a community gathering point.$$,
      'https://images.unsplash.com/photo-1517649763962-0c623066013b?auto=format&fit=crop&w=1400&q=82',
      null::text,
      'sample_seed',
      '2b9b9d11-34d6-4f5f-9a46-7341b4f70003'::uuid
    ),
    (
      '3b9b9d11-34d6-4f5f-9a46-7341b4f70001'::uuid,
      null::text,
      'Community',
      'Amina K.',
      current_date - 3,
      'How I Found My First Running Club',
      $$I used to run alone because I thought I had to become fit before joining a club. The surprise was that the club helped me become fit. My first session was slower than I expected, but nobody treated that as a problem. Someone explained the route, another runner stayed beside me, and the finish felt like an invitation to return.$$,
      'https://images.unsplash.com/photo-1520975682031-a2cfe6aeba80?auto=format&fit=crop&w=1400&q=82',
      null::text,
      'sample_seed',
      '3b9b9d11-34d6-4f5f-9a46-7341b4f70001'::uuid
    ),
    (
      '3b9b9d11-34d6-4f5f-9a46-7341b4f70002'::uuid,
      null::text,
      'Community',
      'Brian O.',
      current_date - 4,
      'The Walk-Run Plan That Helped Me Return',
      $$After months away from exercise, I returned through a walk-run plan that looked almost too simple. Two minutes running, one minute walking, repeated carefully, gave me permission to start again without pretending I was already strong. By the third week I had more confidence, better sleep, and a reason to meet friends after work.$$,
      'https://images.unsplash.com/photo-1501555088652-021faa106b9b?auto=format&fit=crop&w=1400&q=82',
      null::text,
      'sample_seed',
      '3b9b9d11-34d6-4f5f-9a46-7341b4f70002'::uuid
    ),
    (
      '3b9b9d11-34d6-4f5f-9a46-7341b4f70003'::uuid,
      null::text,
      'Community',
      'Club Member Story',
      current_date - 5,
      'Why Our Club Waits For The Last Runner',
      $$Our club has one rule that shapes everything: nobody finishes alone. Faster runners loop back, walkers know they are part of the same session, and new members learn the route without fear of being abandoned. The rule sounds small, but it has changed attendance, confidence, and how people talk about belonging.$$,
      'https://images.unsplash.com/photo-1502224562085-639556652f33?auto=format&fit=crop&w=1400&q=82',
      null::text,
      'sample_seed',
      '3b9b9d11-34d6-4f5f-9a46-7341b4f70003'::uuid
    ),
    (
      '4b9b9d11-34d6-4f5f-9a46-7341b4f70001'::uuid,
      null::text,
      'Columns',
      'Fitness Coach',
      current_date - 6,
      'Build Your Week Around Easy Runs',
      $$Easy runs are often misunderstood because they do not look dramatic. They rarely produce impressive screenshots, yet they are the sessions that allow most runners to repeat training without breaking down. A useful week can begin with one relaxed run, one slightly stronger effort, one mobility session, and enough rest to make the next week possible. The goal is not to prove toughness every day. The goal is to create a rhythm the body can trust.$$,
      'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=1400&q=82',
      null::text,
      'sample_seed',
      '4b9b9d11-34d6-4f5f-9a46-7341b4f70001'::uuid
    ),
    (
      '4b9b9d11-34d6-4f5f-9a46-7341b4f70002'::uuid,
      null::text,
      'Columns',
      'Sports Journalist',
      current_date - 7,
      'What Local Races Teach Us About Community',
      $$Local races reveal the real character of a running community. The headline may mention winners, distances, and medals, but the deeper story is usually found elsewhere. It is in the volunteers who arrive before sunrise, the families waiting near the finish, the marshal who keeps a nervous first-timer on course, and the clubmate who slows down so a friend does not disappear alone.$$,
      'https://images.unsplash.com/photo-1517963879433-6ad2b056d712?auto=format&fit=crop&w=1400&q=82',
      null::text,
      'sample_seed',
      '4b9b9d11-34d6-4f5f-9a46-7341b4f70002'::uuid
    ),
    (
      '4b9b9d11-34d6-4f5f-9a46-7341b4f70003'::uuid,
      null::text,
      'Columns',
      'Empowerment Coach',
      current_date - 8,
      'Start Smaller Than Your Excuse',
      $$Motivation is helpful, but small action is more reliable. Many runners wait for the perfect mood, the perfect shoes, the perfect morning, or the perfect amount of confidence. Those things are pleasant when they appear, but they are poor foundations for a lasting habit. A better beginning is small enough that your excuse has less room to grow.$$,
      'https://images.unsplash.com/photo-1498837167922-ddd27525d352?auto=format&fit=crop&w=1400&q=82',
      null::text,
      'sample_seed',
      '4b9b9d11-34d6-4f5f-9a46-7341b4f70003'::uuid
    ),
    (
      '5b9b9d11-34d6-4f5f-9a46-7341b4f70001'::uuid,
      null::text,
      'Gallery',
      'RunNation Community',
      current_date - 1,
      'Sunrise Start',
      'A calm start before the first easy kilometres.',
      'https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?auto=format&fit=crop&w=1600&q=84',
      null::text,
      'sample_seed',
      '5b9b9d11-34d6-4f5f-9a46-7341b4f70001'::uuid
    ),
    (
      '5b9b9d11-34d6-4f5f-9a46-7341b4f70002'::uuid,
      null::text,
      'Gallery',
      'RunNation Community',
      current_date - 2,
      'Warm-Up Line',
      'A club session begins with movement and laughter.',
      'https://images.unsplash.com/photo-1538805060514-97d9cc17730c?auto=format&fit=crop&w=1600&q=84',
      null::text,
      'sample_seed',
      '5b9b9d11-34d6-4f5f-9a46-7341b4f70002'::uuid
    ),
    (
      '5b9b9d11-34d6-4f5f-9a46-7341b4f70003'::uuid,
      null::text,
      'Gallery',
      'RunNation Community',
      current_date - 3,
      'Route Focus',
      'Steady effort on a quiet road.',
      'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1600&q=84',
      null::text,
      'sample_seed',
      '5b9b9d11-34d6-4f5f-9a46-7341b4f70003'::uuid
    ),
    (
      '5b9b9d11-34d6-4f5f-9a46-7341b4f70004'::uuid,
      null::text,
      'Gallery',
      'RunNation Community',
      current_date - 4,
      'Trail Morning',
      'Fresh air, soft ground, and an unhurried pace.',
      'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1600&q=84',
      null::text,
      'sample_seed',
      '5b9b9d11-34d6-4f5f-9a46-7341b4f70004'::uuid
    ),
    (
      '5b9b9d11-34d6-4f5f-9a46-7341b4f70005'::uuid,
      null::text,
      'Gallery',
      'RunNation Community',
      current_date - 5,
      'Event Gathering',
      'Runners collect at the start before the route opens.',
      'https://images.unsplash.com/photo-1517649763962-0c623066013b?auto=format&fit=crop&w=1600&q=84',
      null::text,
      'sample_seed',
      '5b9b9d11-34d6-4f5f-9a46-7341b4f70005'::uuid
    ),
    (
      '5b9b9d11-34d6-4f5f-9a46-7341b4f70006'::uuid,
      null::text,
      'Gallery',
      'RunNation Community',
      current_date - 6,
      'Training Day',
      'A focused session built around rhythm.',
      'https://images.unsplash.com/photo-1552674605-db6ffd4facb5?auto=format&fit=crop&w=1600&q=84',
      null::text,
      'sample_seed',
      '5b9b9d11-34d6-4f5f-9a46-7341b4f70006'::uuid
    ),
    (
      '5b9b9d11-34d6-4f5f-9a46-7341b4f70007'::uuid,
      null::text,
      'Gallery',
      'RunNation Community',
      current_date - 7,
      'Club Miles',
      'Easy pace, steady conversation, shared route.',
      'https://images.unsplash.com/photo-1502224562085-639556652f33?auto=format&fit=crop&w=1600&q=84',
      null::text,
      'sample_seed',
      '5b9b9d11-34d6-4f5f-9a46-7341b4f70007'::uuid
    ),
    (
      '5b9b9d11-34d6-4f5f-9a46-7341b4f70008'::uuid,
      null::text,
      'Gallery',
      'RunNation Community',
      current_date - 8,
      'Road Rhythm',
      'A clear road and a controlled pace.',
      'https://images.unsplash.com/photo-1483721310020-03333e577078?auto=format&fit=crop&w=1600&q=84',
      null::text,
      'sample_seed',
      '5b9b9d11-34d6-4f5f-9a46-7341b4f70008'::uuid
    ),
    (
      '5b9b9d11-34d6-4f5f-9a46-7341b4f70009'::uuid,
      null::text,
      'Gallery',
      'RunNation Community',
      current_date - 9,
      'Recovery Walk',
      'Gentle movement after a busy training week.',
      'https://images.unsplash.com/photo-1501555088652-021faa106b9b?auto=format&fit=crop&w=1600&q=84',
      null::text,
      'sample_seed',
      '5b9b9d11-34d6-4f5f-9a46-7341b4f70009'::uuid
    ),
    (
      '5b9b9d11-34d6-4f5f-9a46-7341b4f70010'::uuid,
      null::text,
      'Gallery',
      'RunNation Community',
      current_date - 10,
      'Finish Together',
      'The best finish lines feel shared.',
      'https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=1600&q=84',
      null::text,
      'sample_seed',
      '5b9b9d11-34d6-4f5f-9a46-7341b4f70010'::uuid
    )
),
prepared as (
  select
    article_id,
    registration_id,
    page,
    author,
    article_date,
    title,
    case
      when page = 'Gallery' then body
      when page = 'Columns' then body || $$ A column gives the writer room to explain the lesson behind the advice. The first principle is patience. Running rewards repetition more than drama, so a plan should leave the runner able to return tomorrow and next week. The second principle is honesty. A runner should know whether a session is for recovery, endurance, speed, confidence, or connection. Mixing every purpose into one workout often creates pressure without progress. The third principle is community. Even personal goals are easier when people can share routes, ask questions, and celebrate ordinary consistency. For RunNation, a strong column should feel practical enough to use immediately and thoughtful enough to revisit. It should offer a clear idea, explain why it matters, and show how a runner, club, school, institution, charity, or event organizer can apply it. The best guidance helps people see the next possible step and gives them permission to take it well. Good columns should end with one memorable idea and one simple action the reader can try before the week is over, without needing perfect conditions. The advice should remain calm, local, usable, and encouraging for runners who are still building confidence.$$
      else body || $$ A standard magazine story should give readers enough detail to understand why the subject matters without becoming too long for a mobile screen. The strongest pieces include a clear setting, a human reason to care, and one practical takeaway. For RunNation, the tone should remain warm, useful, and inclusive. The story should welcome everyday runners, walkers, clubs, organizers, schools, institutions, charities, and awareness groups. It should show that running is not only about speed. It can also be about friendship, fundraising, health, confidence, and belonging. A good article leaves the reader with a reason to join, support, share, or simply return for the next run.$$
    end as body,
    picture_link,
    external_link,
    source_table,
    source_id
  from sample_articles
)
insert into public.live_magazine (
  article_id,
  registration_id,
  page,
  author,
  article_date,
  title,
  body,
  picture_link,
  external_link,
  source_table,
  source_id
)
select
  article_id,
  registration_id,
  page,
  author,
  article_date,
  title,
  body,
  picture_link,
  external_link,
  source_table,
  source_id
from prepared
on conflict (article_id) do update set
  registration_id = excluded.registration_id,
  page = excluded.page,
  author = excluded.author,
  article_date = excluded.article_date,
  title = excluded.title,
  body = excluded.body,
  picture_link = excluded.picture_link,
  external_link = excluded.external_link,
  source_table = excluded.source_table,
  source_id = excluded.source_id,
  updated_at = now();
