create table if not exists public.medal_goal (
  medal_goal_id bigint generated by default as identity primary key,
  registration_id text not null references public.registrations(registration_id) on delete cascade,
  target_medals integer not null check (target_medals > 0),
  start_date date not null,
  end_date date not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint medal_goal_date_order_check check (end_date >= start_date)
);

create unique index if not exists medal_goal_registration_unique
  on public.medal_goal(registration_id);

create index if not exists idx_medal_goal_registration_dates
  on public.medal_goal(registration_id, start_date, end_date);
