begin;

create extension if not exists pgcrypto;

create table if not exists public.countries (
  iso_alpha2 text primary key,
  name text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.clubs (
  club_id uuid primary key default gen_random_uuid(),
  club_name varchar(255) not null,
  description text null,
  location varchar(255) null,
  coordinator_id text null,
  created_at timestamptz null default now(),
  is_active boolean null default true,
  country text null
);

create table if not exists public.profiles (
  profile_id uuid primary key references auth.users(id) on delete cascade,
  legacy_registration_id uuid unique null references public.registrations(registration_id) on delete set null,
  username text unique,
  display_name text,
  country_code text null references public.countries(iso_alpha2),
  avatar_url text,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.roles (
  role_id bigint generated by default as identity primary key,
  role_name text unique not null
);

insert into public.roles (role_name)
values
  ('super_admin'),
  ('country_admin'),
  ('club_coordinator'),
  ('user')
on conflict (role_name) do nothing;

create table if not exists public.user_role_assignments (
  assignment_id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(profile_id) on delete cascade,
  role_id bigint not null references public.roles(role_id) on delete cascade,
  country_code text null references public.countries(iso_alpha2),
  club_id uuid null references public.clubs(club_id) on delete cascade,
  assigned_by uuid null references public.profiles(profile_id) on delete set null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  constraint user_role_assignments_club_country_check check (
    not (club_id is not null and country_code is not null)
  ),
  constraint unique_role_scope unique nulls not distinct (user_id, role_id, country_code, club_id)
);

create table if not exists public.admin_action_logs (
  log_id bigint generated by default as identity primary key,
  actor_user_id uuid null references public.profiles(profile_id) on delete set null,
  action_type text not null,
  target_user_id uuid null references public.profiles(profile_id) on delete set null,
  target_country_code text null references public.countries(iso_alpha2),
  target_club_id uuid null references public.clubs(club_id) on delete set null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.admin_invites (
  invite_id uuid primary key default gen_random_uuid(),
  email text not null,
  role_id bigint not null references public.roles(role_id) on delete cascade,
  country_code text null references public.countries(iso_alpha2),
  club_id uuid null references public.clubs(club_id) on delete cascade,
  invited_by uuid null references public.profiles(profile_id) on delete set null,
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  expires_at timestamptz null,
  accepted_by uuid null references public.profiles(profile_id) on delete set null,
  constraint admin_invites_status_check check (status in ('pending', 'accepted', 'revoked', 'expired'))
);

create index if not exists idx_profiles_legacy_registration_id
  on public.profiles (legacy_registration_id);

create index if not exists idx_profiles_country_code
  on public.profiles (country_code);

create index if not exists idx_roles_role_name
  on public.roles (role_name);

create index if not exists idx_user_role_assignments_user_id
  on public.user_role_assignments (user_id);

create index if not exists idx_user_role_assignments_role_id
  on public.user_role_assignments (role_id);

create index if not exists idx_user_role_assignments_country_code
  on public.user_role_assignments (country_code)
  where country_code is not null;

create index if not exists idx_user_role_assignments_club_id
  on public.user_role_assignments (club_id)
  where club_id is not null;

create index if not exists idx_admin_action_logs_actor_user_id
  on public.admin_action_logs (actor_user_id);

create index if not exists idx_admin_action_logs_target_country_code
  on public.admin_action_logs (target_country_code)
  where target_country_code is not null;

create index if not exists idx_admin_action_logs_target_club_id
  on public.admin_action_logs (target_club_id)
  where target_club_id is not null;

create index if not exists idx_admin_invites_email
  on public.admin_invites (email);

create or replace function public.handle_new_auth_profile()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (
    profile_id,
    username,
    display_name,
    avatar_url
  )
  values (
    new.id,
    lower(coalesce(new.raw_user_meta_data ->> 'username', split_part(new.email, '@', 1), new.id::text)),
    coalesce(new.raw_user_meta_data ->> 'display_name', new.raw_user_meta_data ->> 'full_name'),
    new.raw_user_meta_data ->> 'avatar_url'
  )
  on conflict (profile_id) do nothing;

  return new;
end;
$$;

create or replace function public.validate_role_scope(
  p_role_id bigint,
  p_country_code text,
  p_club_id uuid
)
returns boolean
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_role_name text;
begin
  select role_name
  into v_role_name
  from public.roles
  where role_id = p_role_id;

  if v_role_name is null then
    return false;
  end if;

  if p_country_code is not null and p_club_id is not null then
    return false;
  end if;

  if v_role_name = 'country_admin' and p_country_code is null then
    return false;
  end if;

  if v_role_name = 'club_coordinator' and p_club_id is null and p_country_code is null then
    return false;
  end if;

  return true;
end;
$$;

create or replace function public.enforce_user_role_assignment_scope()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.validate_role_scope(new.role_id, new.country_code, new.club_id, null::uuid) then
    raise exception 'Invalid role scope for assignment';
  end if;

  return new;
end;
$$;

drop trigger if exists trg_enforce_user_role_assignment_scope on public.user_role_assignments;
create trigger trg_enforce_user_role_assignment_scope
  before insert or update on public.user_role_assignments
  for each row execute function public.enforce_user_role_assignment_scope();

create or replace function public.enforce_admin_invite_scope()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.validate_role_scope(new.role_id, new.country_code, new.club_id, null::uuid) then
    raise exception 'Invalid role scope for invite';
  end if;

  return new;
end;
$$;

drop trigger if exists trg_enforce_admin_invite_scope on public.admin_invites;
create trigger trg_enforce_admin_invite_scope
  before insert or update on public.admin_invites
  for each row execute function public.enforce_admin_invite_scope();

-- Profile creation is handled by the app backend after auth.users creation so
-- auth signup is not blocked by profile-table constraints during development.
drop trigger if exists on_auth_user_created_create_profile on auth.users;

create or replace function public.current_profile_id()
returns uuid
language sql
stable
as $$
  select auth.uid();
$$;

create or replace function public.has_role(
  p_user_id uuid,
  p_role_name text,
  p_country_code text default null,
  p_club_id uuid default null
)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.user_role_assignments ura
    join public.roles r on r.role_id = ura.role_id
    where ura.user_id = p_user_id
      and ura.is_active = true
      and r.role_name = p_role_name
      and (p_country_code is null or ura.country_code = p_country_code)
      and (p_club_id is null or ura.club_id = p_club_id)
  );
$$;

create or replace function public.is_super_admin(p_user_id uuid default auth.uid())
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.user_role_assignments ura
    join public.roles r on r.role_id = ura.role_id
    where ura.user_id = p_user_id
      and ura.is_active = true
      and r.role_name = 'super_admin'
  );
$$;

create or replace function public.is_country_admin(
  p_user_id uuid default auth.uid(),
  p_country_code text default null
)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.user_role_assignments ura
    join public.roles r on r.role_id = ura.role_id
    where ura.user_id = p_user_id
      and ura.is_active = true
      and r.role_name = 'country_admin'
      and (p_country_code is null or ura.country_code = p_country_code)
  );
$$;

create or replace function public.is_club_coordinator(
  p_user_id uuid default auth.uid(),
  p_club_id uuid default null
)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.user_role_assignments ura
    join public.roles r on r.role_id = ura.role_id
    where ura.user_id = p_user_id
      and ura.is_active = true
      and r.role_name = 'club_coordinator'
      and (p_club_id is null or ura.club_id = p_club_id)
  );
$$;

create or replace function public.can_manage_role_assignment(
  p_actor_user_id uuid,
  p_target_role_id bigint,
  p_country_code text default null,
  p_club_id uuid default null
)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  with target_role as (
    select role_name
    from public.roles
    where role_id = p_target_role_id
  )
  select
    public.is_super_admin(p_actor_user_id)
    or exists (
      select 1
      from target_role tr
      where tr.role_name = 'club_coordinator'
        and p_country_code is not null
        and public.is_country_admin(p_actor_user_id, p_country_code)
    );
$$;

create or replace view public.my_active_roles as
select
  ura.assignment_id,
  ura.user_id,
  r.role_name,
  ura.country_code,
  ura.club_id,
  ura.assigned_by,
  ura.created_at
from public.user_role_assignments ura
join public.roles r on r.role_id = ura.role_id
where ura.is_active = true;

alter table public.profiles enable row level security;
alter table public.user_role_assignments enable row level security;
alter table public.admin_action_logs enable row level security;
alter table public.admin_invites enable row level security;

drop policy if exists "profiles_self_select" on public.profiles;
create policy "profiles_self_select"
  on public.profiles
  for select
  using (
    profile_id = auth.uid()
    or public.is_super_admin(auth.uid())
  );

drop policy if exists "profiles_self_update" on public.profiles;
create policy "profiles_self_update"
  on public.profiles
  for update
  using (
    profile_id = auth.uid()
    or public.is_super_admin(auth.uid())
  )
  with check (
    profile_id = auth.uid()
    or public.is_super_admin(auth.uid())
  );

drop policy if exists "role_assignments_select_own" on public.user_role_assignments;
create policy "role_assignments_select_own"
  on public.user_role_assignments
  for select
  using (user_id = auth.uid());

drop policy if exists "role_assignments_select_super_admin" on public.user_role_assignments;
create policy "role_assignments_select_super_admin"
  on public.user_role_assignments
  for select
  using (public.is_super_admin(auth.uid()));

drop policy if exists "role_assignments_select_country_admin_scope" on public.user_role_assignments;
create policy "role_assignments_select_country_admin_scope"
  on public.user_role_assignments
  for select
  using (
    country_code is not null
    and public.is_country_admin(auth.uid(), country_code)
  );

drop policy if exists "role_assignments_insert_manageable" on public.user_role_assignments;
create policy "role_assignments_insert_manageable"
  on public.user_role_assignments
  for insert
  with check (
    user_id <> auth.uid()
    and (
      public.is_super_admin(auth.uid())
      or (
        country_code is not null
        and public.is_country_admin(auth.uid(), country_code)
      )
    )
  );

drop policy if exists "role_assignments_update_manageable" on public.user_role_assignments;
create policy "role_assignments_update_manageable"
  on public.user_role_assignments
  for update
  using (
    public.is_super_admin(auth.uid())
    or (
      country_code is not null
      and public.is_country_admin(auth.uid(), country_code)
    )
  )
  with check (
    user_id <> auth.uid()
    and (
      public.is_super_admin(auth.uid())
      or (
        country_code is not null
        and public.is_country_admin(auth.uid(), country_code)
      )
    )
  );

drop policy if exists "role_assignments_delete_super_admin_only" on public.user_role_assignments;
create policy "role_assignments_delete_super_admin_only"
  on public.user_role_assignments
  for delete
  using (public.is_super_admin(auth.uid()));

drop policy if exists "admin_action_logs_insert_admins" on public.admin_action_logs;
create policy "admin_action_logs_insert_admins"
  on public.admin_action_logs
  for insert
  with check (
    actor_user_id = auth.uid()
    and (
      public.is_super_admin(auth.uid())
      or public.is_country_admin(auth.uid(), target_country_code)
      or public.is_club_coordinator(auth.uid(), target_club_id)
    )
  );

drop policy if exists "admin_action_logs_select_super_admin" on public.admin_action_logs;
create policy "admin_action_logs_select_super_admin"
  on public.admin_action_logs
  for select
  using (public.is_super_admin(auth.uid()));

drop policy if exists "admin_action_logs_select_actor" on public.admin_action_logs;
create policy "admin_action_logs_select_actor"
  on public.admin_action_logs
  for select
  using (actor_user_id = auth.uid());

drop policy if exists "admin_invites_select_super_admin" on public.admin_invites;
create policy "admin_invites_select_super_admin"
  on public.admin_invites
  for select
  using (public.is_super_admin(auth.uid()));

drop policy if exists "admin_invites_select_country_admin" on public.admin_invites;
create policy "admin_invites_select_country_admin"
  on public.admin_invites
  for select
  using (
    country_code is not null
    and public.is_country_admin(auth.uid(), country_code)
  );

drop policy if exists "admin_invites_insert_manageable" on public.admin_invites;
create policy "admin_invites_insert_manageable"
  on public.admin_invites
  for insert
  with check (
    invited_by = auth.uid()
    and (
      public.is_super_admin(auth.uid())
      or (
        country_code is not null
        and public.is_country_admin(auth.uid(), country_code)
      )
    )
  );

drop policy if exists "admin_invites_update_manageable" on public.admin_invites;
create policy "admin_invites_update_manageable"
  on public.admin_invites
  for update
  using (
    public.is_super_admin(auth.uid())
    or (
      country_code is not null
      and public.is_country_admin(auth.uid(), country_code)
    )
  )
  with check (
    public.is_super_admin(auth.uid())
    or (
      country_code is not null
      and public.is_country_admin(auth.uid(), country_code)
    )
  );

comment on table public.profiles is
  'Auth-backed identity profile. legacy_registration_id bridges the existing custom registrations table during migration.';

comment on table public.user_role_assignments is
  'Scoped RBAC assignments. country_code and club_id are nullable; at most one scope is set for a given assignment.';

comment on view public.my_active_roles is
  'Convenience view for reading active role names with their country or club scope.';

commit;
