create table if not exists public.user_goal_pause_periods (
  pause_id bigint generated by default as identity primary key,
  registration_id text not null references public.registrations(registration_id) on delete cascade,
  pause_type text not null check (pause_type in ('injury', 'sick')),
  start_date date not null,
  end_date date null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists user_goal_pause_periods_one_active
  on public.user_goal_pause_periods(registration_id)
  where is_active = true;

create index if not exists idx_user_goal_pause_periods_registration_dates
  on public.user_goal_pause_periods(registration_id, start_date, end_date);
