begin;

create table if not exists public.admin_terms_acceptances (
  acceptance_id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  terms_version text not null,
  accepted_at timestamptz not null default now(),
  accepted_from text not null default 'admin_portal',
  constraint admin_terms_acceptances_unique unique (user_id, terms_version)
);

create index if not exists idx_admin_terms_acceptances_user_id
  on public.admin_terms_acceptances (user_id);

create index if not exists idx_admin_terms_acceptances_terms_version
  on public.admin_terms_acceptances (terms_version);

alter table public.admin_terms_acceptances enable row level security;

drop policy if exists "admin_terms_acceptances_select_own_or_super_admin" on public.admin_terms_acceptances;
create policy "admin_terms_acceptances_select_own_or_super_admin"
  on public.admin_terms_acceptances
  for select
  using (
    user_id = auth.uid()
    or public.is_super_admin(auth.uid())
  );

drop policy if exists "admin_terms_acceptances_insert_own" on public.admin_terms_acceptances;
create policy "admin_terms_acceptances_insert_own"
  on public.admin_terms_acceptances
  for insert
  with check (user_id = auth.uid());

comment on table public.admin_terms_acceptances is
  'Records acceptance of RunNation admin terms by admin-capable users per published terms version.';

commit;
