alter table public.registrations
  add column if not exists smart_watch_brand text,
  add column if not exists smart_watch_model text;

alter table public.activity_approval_notifications
  add column if not exists source_type text;

do $$
begin
  alter table public.activity_approval_notifications
    add constraint activity_approval_notifications_source_type_check
    check (source_type is null or source_type in ('treadmill', 'smart_watch', 'other_sports_app', 'medal_claim'));
exception
  when duplicate_object then null;
end
$$;

insert into public.goals (goal_id, goal)
values
  (8, 'Run Window'),
  (9, 'Running Budget')
on conflict (goal_id) do update
set goal = excluded.goal;

create table if not exists public.run_window_goal (
  run_window_goal_id bigint generated by default as identity primary key,
  registration_id uuid not null references public.registrations(registration_id) on delete cascade,
  start_date date not null,
  end_date date not null,
  regular_windows jsonb not null default '[]'::jsonb,
  event_windows jsonb not null default '[]'::jsonb,
  date_windows jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint run_window_goal_date_check check (end_date >= start_date)
);

create index if not exists idx_run_window_goal_registration_id
  on public.run_window_goal using btree (registration_id);

alter table public.run_window_goal enable row level security;

drop policy if exists "Users can read their run window goals" on public.run_window_goal;
create policy "Users can read their run window goals"
  on public.run_window_goal
  for select
  using (auth.uid() = registration_id);

drop policy if exists "Users can insert their run window goals" on public.run_window_goal;
create policy "Users can insert their run window goals"
  on public.run_window_goal
  for insert
  with check (auth.uid() = registration_id);

drop policy if exists "Users can update their run window goals" on public.run_window_goal;
create policy "Users can update their run window goals"
  on public.run_window_goal
  for update
  using (auth.uid() = registration_id)
  with check (auth.uid() = registration_id);

create table if not exists public.running_budget_goal (
  running_budget_goal_id bigint generated by default as identity primary key,
  registration_id uuid not null references public.registrations(registration_id) on delete cascade,
  start_date date not null,
  end_date date not null,
  budget_amount numeric not null,
  currency text not null default 'USD',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint running_budget_goal_date_check check (end_date >= start_date),
  constraint running_budget_goal_budget_check check (budget_amount > 0)
);

create index if not exists idx_running_budget_goal_registration_id
  on public.running_budget_goal using btree (registration_id);

alter table public.running_budget_goal enable row level security;

drop policy if exists "Users can read their running budget goals" on public.running_budget_goal;
create policy "Users can read their running budget goals"
  on public.running_budget_goal
  for select
  using (auth.uid() = registration_id);

drop policy if exists "Users can insert their running budget goals" on public.running_budget_goal;
create policy "Users can insert their running budget goals"
  on public.running_budget_goal
  for insert
  with check (auth.uid() = registration_id);

drop policy if exists "Users can update their running budget goals" on public.running_budget_goal;
create policy "Users can update their running budget goals"
  on public.running_budget_goal
  for update
  using (auth.uid() = registration_id)
  with check (auth.uid() = registration_id);

create table if not exists public.running_budget_expenses (
  expense_id bigint generated by default as identity primary key,
  running_budget_goal_id bigint not null references public.running_budget_goal(running_budget_goal_id) on delete cascade,
  registration_id uuid not null references public.registrations(registration_id) on delete cascade,
  expense_date date not null default current_date,
  category text not null,
  race_name text,
  other_label text,
  amount numeric not null,
  created_at timestamptz not null default now(),
  constraint running_budget_expenses_amount_check check (amount > 0),
  constraint running_budget_expenses_category_check check (
    category in ('Race registration', 'Transport', 'Lodging', 'Shoes', 'Watch', 'Electrolytes', 'Other')
  )
);

create index if not exists idx_running_budget_expenses_goal
  on public.running_budget_expenses using btree (running_budget_goal_id, expense_date desc);

alter table public.running_budget_expenses enable row level security;

drop policy if exists "Users can read their running budget expenses" on public.running_budget_expenses;
create policy "Users can read their running budget expenses"
  on public.running_budget_expenses
  for select
  using (auth.uid() = registration_id);

drop policy if exists "Users can insert their running budget expenses" on public.running_budget_expenses;
create policy "Users can insert their running budget expenses"
  on public.running_budget_expenses
  for insert
  with check (auth.uid() = registration_id);

drop policy if exists "Users can update their running budget expenses" on public.running_budget_expenses;
create policy "Users can update their running budget expenses"
  on public.running_budget_expenses
  for update
  using (auth.uid() = registration_id)
  with check (auth.uid() = registration_id);
